using NUnit.Framework;
using OpenCobra.OVL;
using OpenCobra.OVL.Files;

namespace OpenCobra.Tests.OVL;

[TestFixture]
public class EnumsTests {
  [Test]
  public void SvdLodType_MatchesOriginalCppLodTypeValues() {
    Assert.That((int) SvdLodType.StaticShape, Is.EqualTo(0));
    Assert.That((int) SvdLodType.BoneShape, Is.EqualTo(3));
    Assert.That((int) SvdLodType.Billboard, Is.EqualTo(4));
  }

  [Test]
  public void SvdFlags_NoShadowAndFlower_ShareTheSameBitValue() {
    Assert.That((uint) SvdFlags.NoShadow, Is.EqualTo((uint) SvdFlags.Flower));
    Assert.That((uint) SvdFlags.NoShadow, Is.EqualTo(0x00000002u));
  }

  [TestCase(FileType.Unknown)]
  [TestCase(FileType.Text)]
  [TestCase(FileType.Integer)]
  [TestCase(FileType.Texture)]
  [TestCase(FileType.Flic)]
  [TestCase(FileType.FlexibleTexture)]
  [TestCase(FileType.GuiSkinItem)]
  [TestCase(FileType.SceneryItem)]
  [TestCase(FileType.BitmapTable)]
  [TestCase(FileType.AnimatedRide)]
  [TestCase(FileType.BoneAnim)]
  [TestCase(FileType.BoneShape)]
  [TestCase(FileType.CarriedItemExtra)]
  [TestCase(FileType.ChangingRoom)]
  [TestCase(FileType.CarriedItem)]
  [TestCase(FileType.ManifoldMesh)]
  [TestCase(FileType.PathType)]
  [TestCase(FileType.QueueType)]
  [TestCase(FileType.RideCar)]
  [TestCase(FileType.RideTrain)]
  [TestCase(FileType.SpecialAttraction)]
  [TestCase(FileType.StaticShape)]
  [TestCase(FileType.Sound)]
  [TestCase(FileType.Spline)]
  [TestCase(FileType.Stall)]
  [TestCase(FileType.SceneryItemVisual)]
  [TestCase(FileType.TerrainType)]
  [TestCase(FileType.TrackSection)]
  [TestCase(FileType.TrackedRide)]
  [TestCase(FileType.WildAnimalItem)]
  [TestCase(FileType.CharacterSkinSet)]
  [TestCase(FileType.CharacterSkinPart)]
  [TestCase(FileType.ParticleSpriteItem)]
  [TestCase(FileType.FontCharacterTable)]
  [TestCase(FileType.Unknown)]
  public void FileType_ToIconName_ReturnsNonEmpty(FileType type) =>
    Assert.That(type.ToIconName(), Is.Not.Empty);

  [TestCase(FileType.Unknown)]
  [TestCase(FileType.Text)]
  [TestCase(FileType.Integer)]
  [TestCase(FileType.Texture)]
  [TestCase(FileType.Flic)]
  [TestCase(FileType.FlexibleTexture)]
  [TestCase(FileType.GuiSkinItem)]
  [TestCase(FileType.SceneryItem)]
  [TestCase(FileType.BitmapTable)]
  [TestCase(FileType.AnimatedRide)]
  [TestCase(FileType.BoneAnim)]
  [TestCase(FileType.BoneShape)]
  [TestCase(FileType.CarriedItemExtra)]
  [TestCase(FileType.ChangingRoom)]
  [TestCase(FileType.CarriedItem)]
  [TestCase(FileType.ManifoldMesh)]
  [TestCase(FileType.PathType)]
  [TestCase(FileType.QueueType)]
  [TestCase(FileType.RideCar)]
  [TestCase(FileType.RideTrain)]
  [TestCase(FileType.SpecialAttraction)]
  [TestCase(FileType.StaticShape)]
  [TestCase(FileType.Sound)]
  [TestCase(FileType.Spline)]
  [TestCase(FileType.Stall)]
  [TestCase(FileType.SceneryItemVisual)]
  [TestCase(FileType.TerrainType)]
  [TestCase(FileType.TrackSection)]
  [TestCase(FileType.TrackedRide)]
  [TestCase(FileType.WildAnimalItem)]
  [TestCase(FileType.CharacterSkinSet)]
  [TestCase(FileType.CharacterSkinPart)]
  [TestCase(FileType.ParticleSpriteItem)]
  [TestCase(FileType.FontCharacterTable)]
  [TestCase(FileType.Unknown)]
  public void FileType_ToGroupIconName_ReturnsNonEmpty(FileType type) =>
    Assert.That(type.ToGroupIconName(), Is.Not.Empty);

  [TestCase(FileType.Text, "txt")]
  [TestCase(FileType.Integer, "int")]
  [TestCase(FileType.Texture, "tex")]
  [TestCase(FileType.Flic, "flic")]
  [TestCase(FileType.FlexibleTexture, "ftx")]
  [TestCase(FileType.GuiSkinItem, "gsi")]
  [TestCase(FileType.SceneryItem, "sid")]
  [TestCase(FileType.BitmapTable, "btbl")]
  [TestCase(FileType.AnimatedRide, "anr")]
  [TestCase(FileType.BoneAnim, "ban")]
  [TestCase(FileType.BoneShape, "bsh")]
  [TestCase(FileType.CarriedItemExtra, "ced")]
  [TestCase(FileType.ChangingRoom, "chg")]
  [TestCase(FileType.CarriedItem, "cid")]
  [TestCase(FileType.ManifoldMesh, "mam")]
  [TestCase(FileType.PathType, "ptd")]
  [TestCase(FileType.QueueType, "qtd")]
  [TestCase(FileType.RideCar, "ric")]
  [TestCase(FileType.RideTrain, "rit")]
  [TestCase(FileType.SpecialAttraction, "sat")]
  [TestCase(FileType.StaticShape, "shs")]
  [TestCase(FileType.Sound, "snd")]
  [TestCase(FileType.Spline, "spl")]
  [TestCase(FileType.Stall, "sta")]
  [TestCase(FileType.SceneryItemVisual, "svd")]
  [TestCase(FileType.TerrainType, "ter")]
  [TestCase(FileType.TrackSection, "tks")]
  [TestCase(FileType.TrackedRide, "trr")]
  [TestCase(FileType.WildAnimalItem, "wai")]
  [TestCase(FileType.CharacterSkinSet, "mms")]
  [TestCase(FileType.CharacterSkinPart, "prt")]
  [TestCase(FileType.ParticleSpriteItem, "psi")]
  [TestCase(FileType.FontCharacterTable, "fct")]
  [TestCase(FileType.Unknown, "")]
  public void FileType_ToTagString_ReturnsCorrectTag(FileType type, string expected) =>
    Assert.That(type.ToTagString(), Is.EqualTo(expected));

  [TestCase(FileType.Text, ".txt")]
  [TestCase(FileType.Integer, ".int")]
  [TestCase(FileType.Texture, ".tex")]
  [TestCase(FileType.Flic, ".flic")]
  [TestCase(FileType.FlexibleTexture, ".ftx")]
  [TestCase(FileType.GuiSkinItem, ".gsi")]
  [TestCase(FileType.SceneryItem, ".sid")]
  [TestCase(FileType.BitmapTable, ".btbl")]
  [TestCase(FileType.AnimatedRide, ".anr")]
  [TestCase(FileType.BoneAnim, ".ban")]
  [TestCase(FileType.BoneShape, ".bsh")]
  [TestCase(FileType.CarriedItemExtra, ".ced")]
  [TestCase(FileType.ChangingRoom, ".chg")]
  [TestCase(FileType.CarriedItem, ".cid")]
  [TestCase(FileType.ManifoldMesh, ".mam")]
  [TestCase(FileType.PathType, ".ptd")]
  [TestCase(FileType.QueueType, ".qtd")]
  [TestCase(FileType.RideCar, ".ric")]
  [TestCase(FileType.RideTrain, ".rit")]
  [TestCase(FileType.SpecialAttraction, ".sat")]
  [TestCase(FileType.StaticShape, ".shs")]
  [TestCase(FileType.Sound, ".snd")]
  [TestCase(FileType.Spline, ".spl")]
  [TestCase(FileType.Stall, ".sta")]
  [TestCase(FileType.SceneryItemVisual, ".svd")]
  [TestCase(FileType.TerrainType, ".ter")]
  [TestCase(FileType.TrackSection, ".tks")]
  [TestCase(FileType.TrackedRide, ".trr")]
  [TestCase(FileType.WildAnimalItem, ".wai")]
  [TestCase(FileType.CharacterSkinSet, ".mms")]
  [TestCase(FileType.CharacterSkinPart, ".prt")]
  [TestCase(FileType.ParticleSpriteItem, ".psi")]
  [TestCase(FileType.FontCharacterTable, ".fct")]
  [TestCase(FileType.Unknown, "")]
  public void FileType_ToTagString_WithAsExtension_ReturnsCorrectExtension(FileType type, string expected) =>
    Assert.That(type.ToTagString(asExtension: expected.Contains(".")), Is.EqualTo(expected));

  [TestCase("txt", FileType.Text)]
  [TestCase("int", FileType.Integer)]
  [TestCase("tex", FileType.Texture)]
  [TestCase("flic", FileType.Flic)]
  [TestCase("ftx", FileType.FlexibleTexture)]
  [TestCase("flt", FileType.FlexibleTexture)]
  [TestCase("gsi", FileType.GuiSkinItem)]
  [TestCase("sid", FileType.SceneryItem)]
  [TestCase("btbl", FileType.BitmapTable)]
  [TestCase("anr", FileType.AnimatedRide)]
  [TestCase("ban", FileType.BoneAnim)]
  [TestCase("bsh", FileType.BoneShape)]
  [TestCase("ced", FileType.CarriedItemExtra)]
  [TestCase("chg", FileType.ChangingRoom)]
  [TestCase("cid", FileType.CarriedItem)]
  [TestCase("mam", FileType.ManifoldMesh)]
  [TestCase("ptd", FileType.PathType)]
  [TestCase("qtd", FileType.QueueType)]
  [TestCase("ric", FileType.RideCar)]
  [TestCase("rit", FileType.RideTrain)]
  [TestCase("sat", FileType.SpecialAttraction)]
  [TestCase("shs", FileType.StaticShape)]
  [TestCase("snd", FileType.Sound)]
  [TestCase("spl", FileType.Spline)]
  [TestCase("sta", FileType.Stall)]
  [TestCase("svd", FileType.SceneryItemVisual)]
  [TestCase("ter", FileType.TerrainType)]
  [TestCase("tks", FileType.TrackSection)]
  [TestCase("trr", FileType.TrackedRide)]
  [TestCase("wai", FileType.WildAnimalItem)]
  [TestCase("mms", FileType.CharacterSkinSet)]
  [TestCase("prt", FileType.CharacterSkinPart)]
  [TestCase("psi", FileType.ParticleSpriteItem)]
  [TestCase("fct", FileType.FontCharacterTable)]
  [TestCase("unknown", FileType.Unknown)]
  [TestCase("", FileType.Unknown)]
  [TestCase("foo", FileType.Unknown)]
  public void String_ToFileType_ReturnsCorrectType(string tag, FileType expected) =>
    Assert.That(tag.ToFileType(), Is.EqualTo(expected));
}
