// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Drawing;

using Foundation;
using AppKit;
using CoreAnimation;
using ObjCRuntime;

namespace OpenRCT3.Platforms.macOS;

public partial class MainWindow : NSWindow, IWindow {
  public MainWindow(NativeHandle handle) : base(handle) => MakeKeyAndOrderFront(this);

  public uint FrameBufferWidth => (uint) Math.Round(
    Controller?.Game.Bounds.Width.Value * BackingScaleFactor.Value ?? 640
  );
  public uint FrameBufferHeight => (uint) Math.Round(
    Controller?.Game.Bounds.Height.Value * BackingScaleFactor.Value ?? 420
  );

  public Size FrameBufferSize => new((int)FrameBufferWidth, (int)FrameBufferHeight);

  public Dpi Dpi => new Dpi((float)BackingScaleFactor.Value, (float)BackingScaleFactor.Value);

  public AppKit.NSObjectPredicate? WindowShouldClose => Controller?.ShouldClose;

  private GameViewController? Controller => ContentViewController as GameViewController;
}
