// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Drawing;

using Foundation;
using AppKit;
using CoreAnimation;
using ObjCRuntime;

namespace OpenRCT3.Platforms.macOS;

public partial class MainWindow : NSWindow, IWindow {
  public MainWindow(NativeHandle handle) : base(handle) => MakeKeyAndOrderFront(this);

  public uint FrameBufferWidth => (uint) Math.Round(
    Controller?.Game.Bounds.Width.Value * BackingScaleFactor.Value ?? 640
  );
  public uint FrameBufferHeight => (uint) Math.Round(
    Controller?.Game.Bounds.Height.Value * BackingScaleFactor.Value ?? 420
  );

  public Size FrameBufferSize => new Size((int)FrameBufferWidth, (int)FrameBufferHeight);

  public Dpi Dpi => new Dpi((float)BackingScaleFactor.Value, (float)BackingScaleFactor.Value);

  private GameViewController? Controller => ContentViewController as GameViewController;

  public override void AwakeFromNib() {
    base.AwakeFromNib();

    Controller?.Surface.SurfaceCreated += SurfaceCreated;
    // TODO: Update framebuffer on WillResize/DidResize, DidChangeScreen, and DidChangeScreenProfile
    // See also DidEndLiveResize
  }

  private static void SurfaceCreated(IGraphicsSurface surface, IRenderer renderer) =>
    // Start the game
    Task.Run(() => new Game(renderer).Run());
}
