// This file has been autogenerated from a class added in the UI designer.

using System;

using ObjCRuntime;
using Foundation;
using AppKit;

namespace Dumper;

public partial class MainWindow : NSWindow {
  public MainWindow(NativeHandle handle) : base(handle) {
    CanBecomeVisibleWithoutLogin = false;
    Delegate = new MainWindowDelegate();
  }

  public override bool CanBecomeMainWindow => true;

  public override void BecomeMainWindow() {
    MakeMainWindow();

    // FIXME: [NSApplication activate]: unrecognized selector sent to instance
    // FIXME: NSApplication.SharedApplication.Activate();
    MakeKeyAndOrderFront(this);
  }
}

internal class MainWindowDelegate : NSWindowDelegate {
  private string subtitle = "";

  public MainWindowDelegate() : base() { }

  public event EventHandler<string>? UpdateSubtitle;

  public override void DidBecomeMain(NSNotification notification) {
    base.DidBecomeMain(notification);
    UpdateSubtitle?.Invoke(this, Subtitle);
  }

  internal string Subtitle {
    get => subtitle;
    set {
      subtitle = value;
      UpdateSubtitle?.Invoke(this, value);
    }
  }
}
