// This file has been autogenerated from a class added in the UI designer.

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Reactive.Linq;
using ObjCRuntime;
using Foundation;
using AppKit;
using Dumper.Documents;
using Dumper.Models;

namespace Dumper;

public sealed partial class MainWindow : NSWindow {
  public MainWindow(NativeHandle handle) : base(handle) { }

  public override bool CanBecomeMainWindow => true;
  public override bool CanBecomeVisibleWithoutLogin => false;

  public override void MakeMainWindow() {
    Debug.Assert(WindowController != null, nameof(WindowController) + " != null");

    base.MakeMainWindow();
    MakeKeyAndOrderFront(this);
  }

  public override void BecomeMainWindow() {
    AppDelegate.Instance.MainWindow = this;
    base.BecomeMainWindow();
  }
}

internal class MainWindowDelegate(Project project) : NSWindowDelegate {
  public event EventHandler? Closing;

  public override void WillClose(NSNotification notification) {
    Closing?.Invoke(this, EventArgs.Empty);
  }

  public override void DidBecomeMain(NSNotification notification) {
    Debug.Assert(project.Name.Length > 0);
  }

  public override void DidResignMain(NSNotification notification) {
    // TODO: Dispose of any reactive observers
  }
}
