name: Website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          cache: true
      - name: Build
        run: make website
      # FIXME: See `make percy`
      # - name: Visual Diff with Percy
      #   if: success()
      #   run: make percy
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "clients/website/_site"

  deploy:
    name: Deploy Website
    needs: build
    runs-on: ubuntu-latest
    # TODO: Deploy pull requests for testing
    if: github.ref == 'refs/heads/main'

    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
